<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ApplicationIcon />
    <StartupObject>CrossNodeUI.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\API_HubTool.Bindings\API_HubTool.Bindings.csproj" />
  </ItemGroup>
</Project>